### ISSUE TITLE
Not able to play music

### ISSUE THREAD

**Issue by shkar62** [Sn8z/Poddr#3]
I have been trying to play track using apple music api. I get the authorisation status to be authorised, however for the capability, I always get none. Can someone assist for the same?

**Comment by Sn8z** [comment]
I'm sorry but this is not the place to discuss issues with Apple Music API in general :/
Issues should relate to Poddr. Poddr doesn't use any authorization at all since we only use the different Apple APIs to lookup searches and toplists, the actual podcast file is fetched from the respective podcasts individual feeds, not from Apple/iTunes itself.

If you need help I suggest you go to [Stack Overflow](https://stackoverflow.com/) or [Apples Developer forums](https://forums.developer.apple.com/welcome).
